/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wannabee.lie

import kotlin.test.Test
import kotlin.test.assertTrue

class GeometryTest {
    /*
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
     */
}
